#!/usr/bin/env node
/**
 * Regenerate src/art.generated.ts from the pictures in assets/art.
 *
 *   node scripts/render-art.mjs            write the module
 *   node scripts/render-art.mjs --preview  also write PNG previews to art-preview/
 *
 * Each picture is rendered at several sizes so the app can use the largest
 * that fits the terminal. See assets/art/CREDITS.md for where they came from.
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import sharp from 'sharp';
import { ansiRows, braille, dither, loadGrey, preview, skyMask, tone } from './art-lib.mjs';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const withPreview = process.argv.includes('--preview');

/** A logistic S-curve on [0, 1]: crushes the mid-greys so edges read. */
const scurve = (k) => (v) => {
  const f = (x) => 1 / (1 + Math.exp(-k * (x - 0.5)));
  return (f(v) - f(0)) / (f(1) - f(0));
};

const PICTURES = {
  /** The amphitheatre from the north-west, sunlit, floating in the dark. */
  colosseum: {
    file: 'colosseum-1870s.jpg',
    crop: { left: 0.09, top: 0.1, width: 0.72, height: 0.62 },
    sizes: { cols: [100, 84, 72, 60, 48] },
    process(t, w, h) {
      const sky = skyMask(t, w, h, { threshold: 0.7 });
      const s = scurve(7);
      return t.map((v, i) => {
        if (sky[i]) return 0;
        const fy = Math.floor(i / w) / h;
        const ground = fy > 0.86 ? Math.max(0, 1 - (fy - 0.86) / 0.14) ** 1.5 : 1;
        return s(v) * ground;
      });
    },
    ditherGamma: 0.6,
    greyGamma: 1.1,
    floor: 0.1,
  },
  /** The Dying Gaul — long called the Dying Gladiator — for the fallen. */
  gaul: {
    file: 'dying-gaul.jpg',
    crop: { left: 0.14, top: 0.2, width: 0.74, height: 0.58 },
    sizes: { rows: [14, 10, 8] },
    tone: { low: 0.42 },
    process: (t) => t.map(scurve(5)),
    ditherGamma: 0.9,
    floor: 0.12,
  },
  /** The Borghese Gladiator mid-lunge, for the victor. */
  borghese: {
    file: 'borghese-gladiator.jpg',
    crop: { left: 0.2, top: 0.02, width: 0.75, height: 0.96 },
    sizes: { rows: [22, 18, 14] },
    tone: { low: 0.25 },
    process: (t) => t.map(scurve(5)),
    ditherGamma: 0.55,
    floor: 0.12,
  },
};

async function render(name, spec, size) {
  const src = join(root, 'assets/art', spec.file);
  const meta = await sharp(src).metadata();
  const aspect = (spec.crop.width * meta.width) / (spec.crop.height * meta.height);
  // A terminal cell is about twice as tall as it is wide, and a Braille
  // cell holds 2×4 dots, so dots come out square.
  const cols = size.cols ?? Math.round(size.rows * 2 * aspect);
  const rows = size.rows ?? Math.round(cols / aspect / 2);
  const w = cols * 2;
  const h = rows * 4;
  const raw = await loadGrey(src, { crop: spec.crop, dotsW: w, dotsH: h, sharpen: 1.6, mirror: spec.mirror });
  const t = spec.process(tone(raw, { low: 0.01, high: 0.99, ...spec.tone }), w, h);
  const bits = dither(t.map((v) => v ** spec.ditherGamma), w, h, { method: 'atkinson' });
  const cells = braille(bits, t.map((v) => v ** (spec.greyGamma ?? 1)), w, h, { floor: spec.floor });
  if (withPreview) {
    mkdirSync(join(root, 'art-preview'), { recursive: true });
    await preview(cells, join(root, 'art-preview', `${name}-${cols}x${rows}.png`));
  }
  return { cols, rows, lines: ansiRows(cells) };
}

// Mirrored statues, so on the verdict screen both always face the centre.
PICTURES.borgheseMirrored = { ...PICTURES.borghese, mirror: true };
PICTURES.gaulMirrored = { ...PICTURES.gaul, mirror: true };

const out = {};
for (const [name, spec] of Object.entries(PICTURES)) {
  const list = spec.sizes.cols ? spec.sizes.cols.map((cols) => ({ cols })) : spec.sizes.rows.map((rows) => ({ rows }));
  out[name] = [];
  for (const size of list) out[name].push(await render(name, spec, size));
  console.log(name, out[name].map((p) => `${p.cols}×${p.rows}`).join('  '));
}

const body = `/**
 * GENERATED by scripts/render-art.mjs from the pictures in assets/art.
 * Do not edit by hand: change the script and run it again.
 *
 * Each picture is dithered Braille, one ANSI string per row, tinted with the
 * terminal's 256-colour grey ramp. Sizes run largest first.
 */

export interface Picture {
  cols: number;
  rows: number;
  lines: string[];
}

export const PICTURES: Record<${Object.keys(out).map((k) => `'${k}'`).join(' | ')}, Picture[]> = ${JSON.stringify(out, null, 1)};
`;
writeFileSync(join(root, 'src/art.generated.ts'), body);
console.log('wrote src/art.generated.ts');
